server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/database.db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console # Enable H2 web console
  main:
    log-startup-info: true # show startup info
  logging:
    level:
      org.springframework.boot.autoconfigure: DEBUG
      org.thymeleaf: DEBUG